version: '3.1'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: marcus
            MONGO_INITDB_ROOT_PASSWORD: marcus

    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: marcus
            ME_CONFIG_MONGODB_ADMINPASSWORD: marcus
            ME_CONFIG_MONGODB_URL: mongodb://marcus:marcus@192.168.3.16:27017/
